[package]
name = "adofai-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_jsonrc = "0.1.0"
serde = "1.0.130"